# Generated by Django 4.2.2 on 2023-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img', upload_to='product_images'),
            preserve_default=False,
        ),
    ]
